import Realm from 'realm';

const FollowingSchema = {
  // define database schema based following response
  name: 'Following',
  primaryKey: 'relation_id',
  properties: {
    relation_id: 'int',
    follower_id: 'int',
    leader_id: 'int',
    status: 'string',
    // created_at: 'date',
    // updated_at: 'date',
    // deleted_at: 'date',
    // follower: {
    //   id: 'int',
    //   name_first: 'string',
    //   name_last: 'string',
    //   name_display: 'string',
    //   name_slug: 'string',
    //   email: 'string',
    //   cell_number: 'string',
    //   cell_carrier: 'string',
    //   status: 'string',
    //   confirmation_code: 'string',
    //   confirmed: 'int',
    //   verified: 'int',
    //   language: 'string',
    //   timezone: 'string',
    //   date_birth: 'date',
    //   timeline_id: 'int',
    //   img_avatar: { type: 'string', default: null },
    //   img_background: { type: 'string', default: null },
    //   gender: { type: 'string', default: 'male' },
    //   picture: 'string',
    //   access_token: { type: 'string', default: null },
    //   registered: { type: 'bool', default: null },
    //   setting: {
    //     id: 'int',
    //     user_id: 'int',
    //     privacy_follow: { type: 'string', default: 'all' },
    //     privacy_follow_confirm: { type: 'string', default: 'all' },
    //     privacy_comment: { type: 'string', default: 'all' },
    //     privacy_post: { type: 'string', default: 'all' },
    //     privacy_timeline_post: { type: 'string', default: 'all' },
    //     privacy_message: { type: 'string', default: 'all' },
    //     email_follow: { type: 'int', default: 0 },
    //     email_post_like: { type: 'int', default: 0 },
    //     email_post_share: { type: 'int', default: 0 },
    //     email_comment_post: { type: 'int', default: 0 },
    //     email_comment_like: { type: 'int', default: 0 },
    //     email_comment_reply: { type: 'int', default: 0 },
    //     created_at: { type: 'date', default: null },
    //     updated_at: { type: 'date', default: null },
    //   },
    // },
    // leader: {
    //   id: 'int',
    //   name_first: 'string',
    //   name_last: 'string',
    //   name_display: 'string',
    //   name_slug: 'string',
    //   email: 'string',
    //   cell_number: { type: 'string', default: null },
    //   cell_carrier: { type: 'string', default: null },
    //   status: 'int',
    //   confirmation_code: 'string',
    //   confirmed: 'int',
    //   verified: 'int',
    //   language: 'string',
    //   timezone: 'string',
    //   date_birth: 'date',
    //   timeline_id: 'int',
    //   img_avatar: { type: 'string', default: null },
    //   img_background: { type: 'string', default: null },
    //   gender: { type: 'string', default: 'male' },
    //   picture: 'string',
    //   access_token: { type: 'string', default: null },
    //   registered: { type: 'bool', default: null },
    //   setting: {
    //     id: 'int',
    //     user_id: 'int',
    //     privacy_follow: { type: 'string', default: 'all' },
    //     privacy_follow_confirm: { type: 'string', default: 'all' },
    //     privacy_comment: { type: 'string', default: 'all' },
    //     privacy_post: { type: 'string', default: 'all' },
    //     privacy_timeline_post: { type: 'string', default: 'all' },
    //     privacy_message: { type: 'string', default: 'all' },
    //     email_follow: { type: 'int', default: 0 },
    //     email_post_like: { type: 'int', default: 0 },
    //     email_post_share: { type: 'int', default: 0 },
    //     email_comment_post: { type: 'int', default: 0 },
    //     email_comment_like: { type: 'int', default: 0 },
    //     email_comment_reply: { type: 'int', default: 0 },
    //     created_at: { type: 'date', default: null },
    //     updated_at: { type: 'date', default: null },
    //   },
    // },
  },
};

// let following = new Realm({ schema: [FollowingSchema] });

export default FollowingSchema;
