language: android
android:
  components:
    - build-tools-23.0.3
    - android-25
    - add-on
    - extra
  before_script:
    - gem install fastlane
  script:
    - cd android && fastlane android beta
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
