import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    flex: 3,
    marginLeft: 16,
    marginRight: 16,
    paddingTop: 10,
    paddingLeft: 14,
    paddingRight: 14,
  },
  textinputStyle: {
    fontSize: 16,
    color: 'black',
    width: 0.75 * width,
    height: 40,
  },
  textcustomfield: {
    fontSize: 28,
    color: 'black',
    width: 0.75 * width,
    height: 40,
  },
  textinputGenderStyle: {
    height: 44,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    borderColor: '#2196F3',
    paddingLeft: 8,
    paddingRight: 1,
    borderWidth: 2,
    borderRadius: 2,
    marginBottom: 6,
    marginTop: 6,
  },
  textinputWrapperStyle: {
    borderColor: '#2196F3',
    borderWidth: 2,
    borderRadius: 2,
    flexDirection: 'column',
    paddingLeft: 8,
    paddingRight: 8,
    marginBottom: 6,
    marginTop: 6,
  },
  textWrapperStyle: {
    borderColor: '#2196F3',
    flexDirection: 'column',
    paddingLeft: 16,
    paddingRight: 8,
    marginBottom: 6,
    marginTop: 6,
  },
  btnReg: {
    backgroundColor: '#2196F3',
    borderRadius: 2,
    elevation: 2,
    paddingBottom: 10,
    height: 50,
    margin: 30,
    flexDirection: 'column',
    paddingTop: 10,
    paddingLeft: 14,
    paddingRight: 14,
  },
  textReg: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  line: {
    borderBottomWidth: 0.8,
    borderColor: 'white',
    marginTop: 20,
    marginBottom: 20,
  },
  fail: {
    color: '#ff0000',
    alignSelf: 'flex-start',
  },
  acceptImg: {
    height: 20,
    width: 20,
    marginTop: 10,
    marginLeft: -40,
  },
  policyStyle: {
    flexDirection: 'row',
    alignSelf: 'center',
  },
  btnGender: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 2,
    height: 65,
    width: width * 0.85 / 2,
    borderWidth: 1,
    borderColor: 'silver',
    paddingTop: 5,
  },
  active: {
    borderWidth: 2,
    borderColor: '#2196F3',
  },
  active2: {
    borderWidth: 2,
    borderColor: '#f2003d',
  },
  errBox: {
    margin: 10,
    borderRadius: 6,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,0,0,0.7)',
    width: 0.75 * width,
    height: 60,
    padding: 10,
  },
  genderStyle: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    borderColor: '#2196F3',
    borderWidth: 0.8,
    borderRadius: 2,
    paddingLeft: 16,
    paddingRight: 8,
    marginBottom: 6,
    marginTop: 6,
    height: 40,
  },
});
export default styles;
