export default {
  follow: 'Ikuti',
  unfollow: 'Berhenti Mengikuti',
  confirmation: 'Konfirmasi',
  question: 'Apakah anda yakin berhenti mengikuti orang ini?',
  yes: 'Ya',
  cancel: 'Batal',
  named: 'bernama',
  nofollower: 'Anda tidak memiliki pengikut ',
  nofollowing: 'Anda tidak mengikuti siapapun, klik cari teman untuk mengikuti',
  findfriend: 'Cari Teman',
  approve: 'Diterima',
  request: 'Permintaan',
  search: 'Pencarian',
  searchResult: 'Hasil Pencarian',
  searchFollower: 'Cari Pengikut',
  searchPeople: 'Cari Orang Yang Ingin Diikuti ',
  searchFollowing: 'Cari Orang yang Kamu Ikuti',
};
