const settings = {
  title: 'Pengaturan',
  account: 'Akun',
  name: 'Nama',
  user_name: 'Nama pengguna',
  birthday: 'Tanggal lahir',
  mobile: 'Nomor ponsel',
  email: 'Email',
  password: 'Kata sandi',
  privacy: 'Privasi',
  notification: 'Notifikasi',
  preference: 'Preferensi',
  ad_Preference: 'Preferensi iklan',
  more_info: 'Informasi lanjut',
  support: 'Dukungan',
  Privacy_policy: 'Kebijakan Privasi',
  tos: 'Ketentuan Layanan',
  licence: 'Lisensi',
  account_action: 'Aksi akun',
  clear_cache: 'Hapus cache',
  log_out: 'Keluar',
  save: 'Simpan',
  alerSuccess: 'Sukses!',
  alertNoInput: "'Kesalahan', 'Masukkan salah atau Tidak ada masukkan'",
  saved: 'Pengaturan disimpan',
  firstnameChange: 'Sukses, nama depan Anda sudah tersimpan',
  lastnameChange: 'Sukses, nama belakang Anda sudah tersimpan',
  noChange: 'Tidak ada perubahan!',
  following: 'Mengikuti',
  follower: 'Pengikut',
  adduser: 'Pencarian Teman',
  signin: 'Masuk',
  register: 'Daftar',
  forgotpass: 'Lupa Kata Sandi',
  profile: 'Profil Pengguna',
  approval: 'Persetujuan',
};
export default settings;
