const settings = {
  title: 'Pengaturan',
  account: 'Akun',
  name: 'Nama',
  user_name: 'Nama pengguna',
  birthday: 'Tanggal lahir',
  mobile: 'Nomor ponsel',
  email: 'Email',
  password: 'Kata sandi',
  privacy: 'Privasi',
  notification: 'Notifikasi',
  preference: 'Preferensi',
  ad_Preference: 'Preferensi iklan',
  more_info: 'Informasi lanjut',
  support: 'Dukungan',
  Privacy_policy: 'Kebijakan Privasi',
  tos: 'Ketentuan Layanan',
  licence: 'Lisensi',
  account_action: 'Aksi akun',
  clear_cache: 'Hapus cache',
  log_out: 'Keluar',
  save: 'Simpan',
  alerSuccess: 'Successfully!',
  alerNoInput: "'Kesalahan', 'Masukkan salah atau Tidak ada masukkan'",
  toast: 'Pengaturan disimpan'
};
export default settings;
