export default {
  follow: 'Follow',
  unfollow: 'Unfollow',
  confirmation: 'Confirmation',
  question: 'Are you sure to unfollow this user?',
  yes: 'Yes',
  cancel: 'Cancel',
  named: 'named',
  nofollower: 'You are not have follower ',
  nofollowing: 'You are not following friend, click search friend button to follow',
  findfriend: 'Search Friend',
  approve: 'Approve',
  request: 'Request',
  search: 'Search',
  searchResult: 'Search Result',
  searchFollower: 'Search Your Follower',
  searchPeople: 'Search People',
  searchFollowing: 'Search Your Following',
};
