import LocalizedStrings from 'react-native-localization';


const register = {
  Register_with: 'Register with:',
  Register_facebook: 'Register with Facebook',
  Register_google: 'Register with Google',
  Register_twitter: 'Register with Twitter',
  Register_email: 'Register with Email',
  first_name: 'First name',
  last_name: 'Last name',
  user_name: 'User name',
  email: 'Email',
  password: 'Password',
  confirm_password: 'Confirm password',
  custom_field: 'Custom field',
  and: 'and',
  Register: 'Register',
  Sign_in: 'Sign in',
  sign_agreement: 'By signing up, you agree to RBCodebase',
  register_agreement: 'By registering, you agree to RBCodebase',
  tos: 'Terms of Service',
  tou: 'Terms of Use',
  Privacy_policy: 'Privacy Policy',
  alert_invalid_email: 'Invalid email',
  alert_username_taken: 'The username already taken',
  alert_username_length: 'The username must be at least 5 charachters or numbers',
  alert_password: 'Password does not match',
  alert_min_password: 'The password must be at least 6 charachters',
  alert_first_name: 'Invalid first name',
  alert_last_name: 'Invalid last name',
  error_name: 'Failed, please check your name field',
  error_username: 'Failed, please check your username field',
  error_email: 'Failed, please check your email field',
  error_password: 'Failed, please check your password field',
  error_gender: 'Failed, please check your gender field',
  error_connection: 'Failed, no internet connection',
  gender: 'Gender',
  male: 'Male',
  female: 'Female',
  selectGenderTitle: 'Pick one',
};

export default register;
