const settings = {
  title: 'Settings',
  account: 'Account',
  name: 'Name',
  user_name: 'Username',
  birthday: 'Birthday',
  mobile: 'Mobile number',
  email: 'Email',
  password: 'Password',
  privacy: 'Privacy Policy',
  notification: 'Notification',
  preference: 'Preference',
  ad_Preference: 'Ad Preference',
  more_info: 'More information',
  support: 'Support',
  Privacy_policy: 'Privacy Policy',
  tos: 'Terms of Services',
  licence: 'Licences',
  account_action: 'Account Actions',
  clear_cache: 'Clear cache',
  log_out: 'Log out',
  save: 'Save',
  alertSuccess: 'Success!',
  alertNoInput: 'You have invalid input or you have no input',
  noChange: 'Nothing Changed!',
  lastnameChange: 'Success, your last name has been changed',
  firstnameChange: 'Success, your first name has been changed',
  saved: 'Setting saved',
  error: 'Failed to save setting',
  following: 'Following',
  follower: 'Follower',
  adduser: 'Search Friend',
  signin: 'Sign In',
  register: 'Register',
  forgotpass: 'Forgot Password',
  profile: 'User Profile',
  approval: 'Approval',
  emailVarification: 'emailVarification',
  privacysetting: 'Privacy Setting',
  emailsetting: 'Email Setting',
  gender: 'Gender',
  changegender: 'Change Gender',

};

export default settings;
