const settings = {
  title: 'Settings',
  account: 'Account',
  name: 'Name',
  user_name: 'Username',
  birthday: 'Birthday',
  mobile: 'Mobile number',
  email: 'Email',
  password: 'Password',
  privacy: 'Privacy',
  notification: 'Notification',
  preference: 'Preference',
  ad_Preference: 'Ad Preference',
  more_info: 'More information',
  support: 'Support',
  Privacy_policy: 'Privacy Policy',
  tos: 'Terms of Services',
  licence: 'Licences',
  account_action: 'Account Actions',
  clear_cache: 'Clear cache',
  log_out: 'Log out',
  save: 'Save',
  alertSuccess: 'Success!',
  alerNoInput: "'Error', 'You have invalid input or You have no input'",
  toast: 'Setting saved',
  following: 'Following',
  follower: 'Follower',
  adduser: 'Search Friend',
  signin: 'Sign In',
  register: 'Register',
  forgotpass: 'Forgot Password',
};

export default settings;
