# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hikerapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hikerapp
  # Pods for hikerapp
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
  pod 'Google/SignIn'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'TwitterKit'
  pod 'GoogleToolboxForMac', '2.1.1'
  target 'hikerappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
